### ISSUE TITLE
Using URL directly 

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio-viewer#11]
How to use this formio-viewer as the `https://formview.io/#/examples/example` rather then manually input the url and click the show form button. 
Is there a way that i store this file and just by the url it will show the forms rather than the manual entry.

And the viewer show/render the `wizard` as the page1 page2 button and  not the slider animation thing. 
It would be good if the viewer render the `wizard` forms as it is and dynamic based on the url rather than the manual entry of forms every time.

**Comment by almereyda** [comment]
The live version at pro.formview.io knows a URL parameter `src`.

    https://pro.formview.io/#/?src=

I could be a good idea to mimic this behaviour here in the FLOSS version.
